version: '2'
services:
  web:
    container_name: contenedor_nutition_ger
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "5000:80"
    volumes:
      - ./app:/app
